//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_BIA.Net_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int Id { get; set; }
        public string EmailInvitation { get; set; }
        public Nullable<System.Guid> SecurityTokenInvitation { get; set; }
    
        public virtual Family Famille { get; set; }
        public virtual AspNetUsers AspNetUser { get; set; }
        public virtual FamilyRole FamilyRole { get; set; }
    }
}
