//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$
{
    using System;
    using BIA.Net.Model;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    #pragma warning disable CS1591 // Missing XML Comment
    public partial class ExampleTable3 : ObjectRemap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExampleTable3()
        {
            this.ExampleTable1 = new HashSet<ExampleTable1>();
        }
    
        
        [Required]
        public int Id { get; set; }
        
        [StringLength(50)]
        [Required]
        public string Title { get; set; }
        
        [StringLength(200)]
        [Required]
        public string Description { get; set; }
        
        [Required]
        public short Value { get; set; }
        
        [DisplayFormat(DataFormatString = "{0:n4}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> MyDecimal { get; set; }
        
        public Nullable<double> MyDouble { get; set; }
        
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DateOnly { get; set; }
        
        [DisplayFormat(DataFormatString = "{0:g}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DateAndTime { get; set; }
        
        [DisplayFormat(DataFormatString = "{0:t}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> TimeOnly { get; set; }
        
        public Nullable<System.TimeSpan> MyTimeSpan { get; set; }
        
        /// <summary>
        ///  - Flag:"Time"
        /// </summary>
        public Nullable<long> TimeSpanOver24H { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        
        public virtual ICollection<ExampleTable1> ExampleTable1 { get; set; }
        
        [Required]
        public virtual Site Site { get; set; }
    }
    #pragma warning restore CS1591 // Missing XML Comment
}
