//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$
{
    using System;
    using BIA.Net.Model;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    #pragma warning disable CS1591 // Missing XML Comment
    public partial class User : ObjectRemap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Members = new HashSet<Member>();
        }
    
        
        [Required]
        public int Id { get; set; }
        
        [StringLength(256)]
        public string Email { get; set; }
        
        [StringLength(50)]
        [Required]
        public string FirstName { get; set; }
        
        [StringLength(50)]
        [Required]
        public string LastName { get; set; }
        
        [StringLength(50)]
        [Required]
        public string Login { get; set; }
        
        [StringLength(250)]
        [Required]
        public string DistinguishedName { get; set; }
        
        [Required]
        public bool IsEmployee { get; set; }
        
        [Required]
        public bool IsExternal { get; set; }
        
        [StringLength(50)]
        public string ExternalCompany { get; set; }
        
        [StringLength(50)]
        [Required]
        public string Company { get; set; }
        
        [StringLength(50)]
        [Required]
        public string Site { get; set; }
        
        [StringLength(250)]
        public string Manager { get; set; }
        
        [StringLength(50)]
        [Required]
        public string Department { get; set; }
        
        [StringLength(50)]
        public string SubDepartment { get; set; }
        
        [StringLength(20)]
        [Required]
        public string Office { get; set; }
        
        [StringLength(10)]
        [Required]
        public string Country { get; set; }
        
        [Required]
        public bool DAIEnable { get; set; }
        
        [Required]
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public System.DateTime DAIDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        
        public virtual ICollection<Member> Members { get; set; }
    }
    #pragma warning restore CS1591 // Missing XML Comment
}
