//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$
{
    using System;
    using BIA.Net.Model;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    #pragma warning disable CS1591 // Missing XML Comment
    public partial class Version : ObjectRemap
    {
        
        [Required]
        public int Id { get; set; }
        
        [StringLength(50)]
        [Required]
        public string Name { get; set; }
        
        [StringLength(50)]
        [Required]
        public string Value { get; set; }
    }
    #pragma warning restore CS1591 // Missing XML Comment
}
