//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZZCompanyNameZZ.ZZProjectNameZZ.Model
{
    using System;
    using BIA.Net.Model;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    #pragma warning disable CS1591 // Missing XML Comment
    public partial class ExampleTable1 : ObjectRemap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExampleTable1()
        {
            this.Description = "Description by default";
            this.Date = new DateTime(636503616000000000, DateTimeKind.Unspecified);
            this.ExampleTable3 = new HashSet<ExampleTable3>();
        }
    
        
        [Required]
        public int Id { get; set; }
        
        [StringLength(10)]
        [Required]
        public string Title { get; set; }
        
        [StringLength(200)]
        [Required]
        public string Description { get; set; }
        
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Date { get; set; }
    
        
        [Required]
        public virtual ExampleTable2 ExampleTable2 { get; set; }
        
        public virtual ExampleTable2 ExampleTable2_0_1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        
        public virtual ICollection<ExampleTable3> ExampleTable3 { get; set; }
        
        [Required]
        public virtual Site Site { get; set; }
    }
    #pragma warning restore CS1591 // Missing XML Comment
}
