//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZZCompanyNameZZ.ZZProjectNameZZ.Model
{
    using System;
    using BIA.Net.Model;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    #pragma warning disable CS1591 // Missing XML Comment
    public partial class ExampleTable2 : ObjectRemap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExampleTable2()
        {
            this.ExampleTable1 = new HashSet<ExampleTable1>();
            this.ExampleTable11 = new HashSet<ExampleTable1>();
        }
    
        
        [Required]
        public int Id { get; set; }
        
        [StringLength(10)]
        [Required]
        public string Title { get; set; }
        
        [StringLength(200)]
        [Required]
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        
        public virtual ICollection<ExampleTable1> ExampleTable1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        
        public virtual ICollection<ExampleTable1> ExampleTable11 { get; set; }
        
        [Required]
        public virtual Site Site { get; set; }
    }
    #pragma warning restore CS1591 // Missing XML Comment
}
