//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZZCompanyNameZZ.ZZProjectNameZZ.Model
{
    using System;
    using BIA.Net.Model;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    #pragma warning disable CS1591 // Missing XML Comment
    public partial class Member : ObjectRemap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.MemberRole = new HashSet<MemberRole>();
        }
    
        
        [Required]
        public int Id { get; set; }
    
        
        [Required]
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        
        public virtual ICollection<MemberRole> MemberRole { get; set; }
        
        [Required]
        public virtual Site Site { get; set; }
    }
    #pragma warning restore CS1591 // Missing XML Comment
}
