//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZZCompanyNameZZ.ZZProjectNameZZ.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    #pragma warning disable CS1591 // Missing XML Comment
    public partial class ZZProjectNameZZDBContainer : DbContext
    {
        public ZZProjectNameZZDBContainer()
            : base("name=ZZProjectNameZZDBContainer")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ExampleTable1> ExampleTable1 { get; set; }
        public virtual DbSet<ExampleTable2> ExampleTable2 { get; set; }
        public virtual DbSet<ExampleTable3> ExampleTable3 { get; set; }
        public virtual DbSet<Version> Version { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<MemberRole> MemberRole { get; set; }
        public virtual DbSet<Site> Site { get; set; }
        public virtual DbSet<View> View { get; set; }
        public virtual DbSet<SiteView> SiteViews { get; set; }
        public virtual DbSet<UserView> UserViews { get; set; }
    }
    #pragma warning restore CS1591 // Missing XML Comment
}
