export enum Permission {
  Home_Access = 'Home_Access',
  Member_Create = 'Member_Create',
  Member_Delete = 'Member_Delete',
  Member_List_Access = 'Member_List_Access',
  Member_Read = 'Member_Read',
  Member_Save = 'Member_Save',
  Member_Update = 'Member_Update',
  // Begin BIADemo
  Plane_Create = 'Plane_Create',
  Plane_Delete = 'Plane_Delete',
  Plane_List_Access = 'Plane_List_Access',
  Plane_Read = 'Plane_Read',
  Plane_Save = 'Plane_Save',
  Plane_Update = 'Plane_Update',
  // End BIADemo
  Roles_List = 'Roles_List',
  Site_Create = 'Site_Create',
  Site_Delete = 'Site_Delete',
  Site_List_Access = 'Site_List_Access',
  Site_Read = 'Site_Read',
  Site_Save = 'Site_Save',
  Site_Update = 'Site_Update',
  User_Add = 'User_Add',
  User_Delete = 'User_Delete',
  User_List = 'User_List',
  User_ListAD = 'User_ListAD',
  User_List_Access = 'User_List_Access',
  User_Sync = 'User_Sync',
  View_List = 'View_List',
  View_Delete_UserView = 'View_Delete_UserView',
  View_Delete_SiteView = 'View_Delete_SiteView',
  View_Set_Default_UserView= "View_Set_Default_UserView"
}
